
package projetoint;

import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class MenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form CrudAppFrame
     */
    private int IdUsuarioSelecionado = -1;
    
    public MenuInicial() {
        initComponents();
        /*try {
            loadUserData();
            
        } catch (SQLException ex) {
            Logger.getLogger(MenuInicial.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        X = new java.awt.Button();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        verdoacoesButton = new javax.swing.JButton();
        doarButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        X.setActionCommand("X");
        X.setLabel("button1");
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 200));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SEJA BEM-VINDO AO DANONATION");
        jLabel1.setMaximumSize(new java.awt.Dimension(215, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(215, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(215, 80));

        verdoacoesButton.setBackground(new java.awt.Color(204, 0, 204));
        verdoacoesButton.setText("VER DOAÇÕES");
        verdoacoesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdoacoesButtonActionPerformed(evt);
            }
        });

        doarButton.setBackground(new java.awt.Color(0, 102, 51));
        doarButton.setText("DOAR");
        doarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doarButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("O DanoNation é uma plataforma de doações simples, segura e transparente, \ncriada para conectar pessoas que querem ajudar a causas que realmente fazem a diferença. \nAqui, cada doação vira impacto real — apoiando projetos, iniciativas sociais e quem precisa de apoio para\n transformar histórias e construir um futuro melhor. 💙");
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(verdoacoesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(doarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verdoacoesButton)
                    .addComponent(doarButton))
                .addGap(176, 176, 176))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verdoacoesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdoacoesButtonActionPerformed
        
        /*String addNome = nomeTextField.getText();
        String addSobrenome = sobrenomeTextField.getText();
        String addEmail = emailTextField.getText();
        String addCidade = cidadeTextField.getText();
        
        if(addNome.isEmpty() || addSobrenome.isEmpty() || addEmail.isEmpty() || addCidade.isEmpty()){
            
           JOptionPane.showMessageDialog(this, "Por favor preencha todos os campos","ERRO",JOptionPane.ERROR_MESSAGE);
            
        }else{
            
            if(IdUsuarioSelecionado != -1){
                
                Usuario AtualizarUsuario = new Usuario(IdUsuarioSelecionado, addNome, addSobrenome, addEmail, addCidade);
                UsuarioDAO usuarioDao;
                try{
                    
                    usuarioDao = new UsuarioDAO();
                    int res = usuarioDao.updateUsuario(AtualizarUsuario);
                    if(res == 1){
                        
                        JOptionPane.showMessageDialog(this, "Usuario atualizado com sucesso", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
                        this.clearForm();
                        loadUserData();
                        IdUsuarioSelecionado = -1;
                        
                    }else{
                        
                        JOptionPane.showMessageDialog(this, "Erro ao atualizar", "ERRO", JOptionPane.ERROR_MESSAGE);
                        
                    }
                    
                }catch(SQLException e){
                    
                    JOptionPane.showMessageDialog(this, "Erro ao atualizar", "ERRO", JOptionPane.ERROR_MESSAGE);
                    
                }
                
            }else{
                
                JOptionPane.showMessageDialog(this, "Erro ao atualizar", "ERRO", JOptionPane.ERROR_MESSAGE);
                
            }
            
        }*/
        
    }//GEN-LAST:event_verdoacoesButtonActionPerformed

    private void doarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doarButtonActionPerformed
        
        /*if(IdUsuarioSelecionado != -1){
            
            int confirmacao = JOptionPane.showConfirmDialog(this, "Você tem certeza que quer deletar esse usuario?", "Confirme a ação", JOptionPane.YES_NO_OPTION);
            if(confirmacao == JOptionPane.YES_OPTION){
                
                UsuarioDAO usuarioDao;
                try{
                    
                    usuarioDao = new UsuarioDAO();
                    usuarioDao.deleteUsuario(IdUsuarioSelecionado);
                    JOptionPane.showMessageDialog(this, "Usuario deletado com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    this.clearForm();
                    loadUserData();
                    IdUsuarioSelecionado = -1;
                    
                }catch(SQLException e){
                    
                    JOptionPane.showMessageDialog(this, "Erro ao deletar", "ERRO", JOptionPane.ERROR_MESSAGE);
                    
                }
                
            }
            
        }else{
            
            JOptionPane.showMessageDialog(this, "Nenhum usuário selecionado", "ERRO", JOptionPane.ERROR_MESSAGE);
            
        }*/
        
    }//GEN-LAST:event_doarButtonActionPerformed

    private void XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button X;
    private javax.swing.JButton doarButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton verdoacoesButton;
    // End of variables declaration//GEN-END:variables

    /*private void clearForm() {
        
        nomeTextField.setText("");
        sobrenomeTextField.setText("");
        emailTextField.setText("");
        cidadeTextField.setText("");
        
    }

    private void loadUserData() throws SQLException {
        
        UsuarioDAO userDao = new UsuarioDAO();
        List<Usuario> usuarios = userDao.getUsuarios();
        String[][] data = new String[usuarios.size()][5];
        
        //Preenchendo a tabela (colunas e linhas)
        for (int i = 0; i < usuarios.size(); i++) {
            
            data[i][0] = String.valueOf(usuarios.get(i).getId());
            data[i][1] = usuarios.get(i).getNome();
            data[i][2] = usuarios.get(i).getSobrenome();
            data[i][3] = usuarios.get(i).getEmail();
            data[i][4] = usuarios.get(i).getCidade();
            
        }
        String[] nomeColuna = {"Id","Nome","Sobrenome","Email","Cidade"};
        Tabela_Usuarios.setModel(new javax.swing.table.DefaultTableModel(data,nomeColuna));
        
    }*/
}
