/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javacrudapp;

import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author RYANGABRIELDAROSA
 */
public class CrudAppFrame extends javax.swing.JFrame {

    /**
     * Creates new form CrudAppFrame
     */
    private int IdUsuarioSelecionado = -1;
    
    public CrudAppFrame() {
        initComponents();
        //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        sobrenomeTextField = new javax.swing.JTextField();
        cidadeTextField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        atualizarButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela_Usuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 200));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CRUD COM INTERFACE GRÁFICA");

        jLabel2.setText("Nome");

        jLabel3.setText("Email");

        jLabel4.setText("Sobrenome");

        jLabel5.setText("Cidade");

        addButton.setBackground(new java.awt.Color(51, 153, 0));
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        atualizarButton.setBackground(new java.awt.Color(0, 0, 204));
        atualizarButton.setText("ATUALIZAR");
        atualizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarButtonActionPerformed(evt);
            }
        });

        delButton.setBackground(new java.awt.Color(255, 0, 0));
        delButton.setText("DELETAR");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButton)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(atualizarButton)
                        .addGap(18, 18, 18)
                        .addComponent(delButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cidadeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(sobrenomeTextField))
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sobrenomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(atualizarButton)
                    .addComponent(delButton))
                .addGap(38, 38, 38))
        );

        Tabela_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Sobrenome", "Email", "Cidade"
            }
        ));
        Tabela_Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_UsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tabela_Usuarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarButtonActionPerformed
        
        String addNome = nomeTextField.getText();
        String addSobrenome = sobrenomeTextField.getText();
        String addEmail = emailTextField.getText();
        String addCidade = cidadeTextField.getText();
        
        if(addNome.isEmpty() || addSobrenome.isEmpty() || addEmail.isEmpty() || addCidade.isEmpty()){
            
           JOptionPane.showMessageDialog(this, "Por favor preencha todos os campos","ERRO",JOptionPane.ERROR_MESSAGE);
            
        }else{
            
            if(IdUsuarioSelecionado != -1){
                
                Usuario AtualizarUsuario = new Usuario(IdUsuarioSelecionado, addNome, addSobrenome, addEmail, addCidade);
                UsuarioDAO usuarioDao;
                try{
                    
                    usuarioDao = new UsuarioDAO();
                    int res = usuarioDao.updateUsuario(AtualizarUsuario);
                    if(res == 1){
                        
                        JOptionPane.showMessageDialog(this, "Usuario atualizado com sucesso", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
                        this.clearForm();
                        loadUserData();
                        IdUsuarioSelecionado = -1;
                        
                    }else{
                        
                        JOptionPane.showMessageDialog(this, "Erro ao atualizar", "ERRO", JOptionPane.ERROR_MESSAGE);
                        
                    }
                    
                }catch(SQLException e){
                    
                    JOptionPane.showMessageDialog(this, "Erro ao atualizar", "ERRO", JOptionPane.ERROR_MESSAGE);
                    
                }
                
            }else{
                
                JOptionPane.showMessageDialog(this, "Erro ao atualizar", "ERRO", JOptionPane.ERROR_MESSAGE);
                
            }
            
        }
        
    }//GEN-LAST:event_atualizarButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
       
        String addNome = nomeTextField.getText();
        String addSobrenome = sobrenomeTextField.getText();
        String addEmail = emailTextField.getText();
        String addCidade = cidadeTextField.getText();
        
        if(addNome.isEmpty() || addSobrenome.isEmpty() || addEmail.isEmpty() || addCidade.isEmpty()){
            
            JOptionPane.showMessageDialog(this, "Por favor preencha todos os campos","ERRO",JOptionPane.ERROR_MESSAGE);
            
        }else{
            
            Usuario novoUsuario = new Usuario(0, addNome,addSobrenome,addEmail,addCidade);
            UsuarioDAO userDao;
            
            try{
                
                userDao = new UsuarioDAO();
                int res = userDao.InserirUsuario(novoUsuario);
                if(res == 1){
                    
                   JOptionPane.showMessageDialog(this, "Usuário criado com seucesso!","SUCESSO",JOptionPane.INFORMATION_MESSAGE);
                   this.clearForm();
                   loadUserData(); //Carregamento de dados do usuario
                   
                }else{
                    
                    JOptionPane.showMessageDialog(this, "Erro ocorrido ao inserir o usuário","ERRO",JOptionPane.ERROR_MESSAGE);
                    
                }
                
            }catch(SQLException e){
                
                JOptionPane.showMessageDialog(this, "Erro ocorrido ao inserir o usuário","ERRO",JOptionPane.ERROR_MESSAGE);
                
            }
            
        }
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        
        if(IdUsuarioSelecionado != -1){
            
            int confirmacao = JOptionPane.showConfirmDialog(this, "Você tem certeza que quer deletar esse usuario?", "Confirme a ação", JOptionPane.YES_NO_OPTION);
            if(confirmacao == JOptionPane.YES_OPTION){
                
                UsuarioDAO usuarioDao;
                try{
                    
                    usuarioDao = new UsuarioDAO();
                    usuarioDao.deleteUsuario(IdUsuarioSelecionado);
                    JOptionPane.showMessageDialog(this, "Usuario deletado com sucesso", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                    this.clearForm();
                    loadUserData();
                    IdUsuarioSelecionado = -1;
                    
                }catch(SQLException e){
                    
                    JOptionPane.showMessageDialog(this, "Erro ao deletar", "ERRO", JOptionPane.ERROR_MESSAGE);
                    
                }
                
            }
            
        }else{
            
            JOptionPane.showMessageDialog(this, "Nenhum usuário selecionado", "ERRO", JOptionPane.ERROR_MESSAGE);
            
        }
        
    }//GEN-LAST:event_delButtonActionPerformed

    private void Tabela_UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_UsuariosMouseClicked
       
        int linhaSelecionada = Tabela_Usuarios.getSelectedRow();
        
        if(linhaSelecionada != -1){
            
            IdUsuarioSelecionado = Integer.parseInt(Tabela_Usuarios.getValueAt(linhaSelecionada, 0).toString());
            nomeTextField.setText(Tabela_Usuarios.getValueAt(linhaSelecionada, 1).toString());
            sobrenomeTextField.setText(Tabela_Usuarios.getValueAt(linhaSelecionada, 2).toString());
            emailTextField.setText(Tabela_Usuarios.getValueAt(linhaSelecionada, 3).toString());
            cidadeTextField.setText(Tabela_Usuarios.getValueAt(linhaSelecionada, 4).toString());
            
        }
        
    }//GEN-LAST:event_Tabela_UsuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudAppFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela_Usuarios;
    private javax.swing.JButton addButton;
    private javax.swing.JButton atualizarButton;
    private javax.swing.JTextField cidadeTextField;
    private javax.swing.JButton delButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JTextField sobrenomeTextField;
    // End of variables declaration//GEN-END:variables

    private void clearForm() {
        
        nomeTextField.setText("");
        sobrenomeTextField.setText("");
        emailTextField.setText("");
        cidadeTextField.setText("");
        
    }

    private void loadUserData() throws SQLException {
        
        UsuarioDAO userDao = new UsuarioDAO();
        List<Usuario> usuarios = userDao.getUsuarios();
        String[][] data = new String[usuarios.size()][5];
        
        //Preenchendo a tabela (colunas e linhas)
        for (int i = 0; i < usuarios.size(); i++) {
            
            data[i][0] = String.valueOf(usuarios.get(i).getId());
            data[i][1] = usuarios.get(i).getNome();
            data[i][2] = usuarios.get(i).getSobrenome();
            data[i][3] = usuarios.get(i).getEmail();
            data[i][4] = usuarios.get(i).getCidade();
            
        }
        String[] nomeColuna = {"Id","Nome","Sobrenome","Email","Cidade"};
        Tabela_Usuarios.setModel(new javax.swing.table.DefaultTableModel(data,nomeColuna));
        
    }
}
