
package Danonation;
import java.sql.SQLException;
import java.util.List;

/**
 *
 * @author RYANGABRIELDAROSA
 */
public class ListaDonations extends javax.swing.JFrame {

    /**
     * Creates new form ListaDonations
     */
    public ListaDonations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDanonations = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaDanonations.setAutoCreateRowSorter(true);
        listaDanonations.setBackground(new java.awt.Color(153, 153, 153));
        listaDanonations.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        listaDanonations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome do doador", "Sobrenome do doador", "Telefone", "Item doado", "Quantidade", "Validade"
            }
        ));
        listaDanonations.setMinimumSize(new java.awt.Dimension(200, 400));
        listaDanonations.setRowHeight(60);
        listaDanonations.setShowGrid(false);
        listaDanonations.setShowHorizontalLines(true);
        listaDanonations.setShowVerticalLines(true);
        listaDanonations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaDanonationsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaDanonations);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1896, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaDanonationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaDanonationsMouseClicked
        // TODO add your handling code here:
        
         /*int linhaSelecionada = ListaDonations.getSelectedRow();
        
        if(linhaSelecionada != -1){
            
            IdDoacaoSelecionado = Integer.parseInt(ListaDonations.getValueAt(linhaSelecionada, 0).toString());
            NomeD.setText(ListaDonations.getValueAt(linhaSelecionada, 1).toString());
            SobreD.setText(ListaDonations.getValueAt(linhaSelecionada, 2).toString());
            TelD.setText(ListaDonations.getValueAt(linhaSelecionada, 3).toString());
            ItemD.setText(ListaDonations.getValueAt(linhaSelecionada, 4).toString());
            QuantD.setText(ListaDonations.getValueAt(linhaSelecionada, 5).toString());
            DataV.setText(ListaDonations.getValueAt(linhaSelecionada, 4).toString());
            
        }*/
        
    }//GEN-LAST:event_listaDanonationsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaDonations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaDonations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaDonations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaDonations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaDonations().setVisible(true);
            }
        });
    }
    
    /*private void clearForm() {
        
        NomeD.setText("");
        SobreD.setText("");
        TelD.setText("");
        ItemD.setText("");
        QuantD.setText("");
        DataV.setText("");
        
    }

    private void loadUserData() throws SQLException { 
        
        DoacaoDAO userDao = new DoacaoDAO();
        List<Doacao> doacoes = userDao.getDoacoes();
        String[][] data = new String[doacoes.size()][5];
        
        //Preenchendo a tabela (colunas e linhas)
      for (int i = 0; i < doacoes.size(); i++) {
            
            data[i][0] = String.valueOf(doacoes.get(i).getId());
            data[i][1] = doacoes.get(i).getNome();
            data[i][2] = doacoes.get(i).getSobrenome();
            data[i][3] = doacoes.get(i).getNumero();
            data[i][4] = doacoes.get(i).getItem();
            data[i][5] = doacoes.get(i).getQuant();
            data[i][6] = doacoes.get(i).getData();
            
        }
        
        String[] nomeColuna = {"Id","Nome","Sobrenome","Telefone","Item doado","Quantidade","Data"};
        //ListaDonations.setModel(new javax.swing.table.DefaultTableModel(data,nomeColuna));
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaDanonations;
    // End of variables declaration//GEN-END:variables
}
