/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoint;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author RYANGABRIELDAROSA
 */
public class Cadastro extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
         try {
            loadUserData();
            
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        setTitle("");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NomeDoador = new javax.swing.JTextField();
        Nome = new javax.swing.JLabel();
        Sobrenome = new javax.swing.JLabel();
        SobreDoador = new javax.swing.JTextField();
        Idade = new javax.swing.JLabel();
        IdadeDoador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        BotaoCadastrar = new javax.swing.JButton();
        CaixadeVerificacao = new javax.swing.JCheckBox();
        BackButton = new javax.swing.JButton();
        CPFDoador2 = new javax.swing.JFormattedTextField();
        TelefoneDFormattedTextField = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        NomeDoador.setBackground(new java.awt.Color(255, 255, 255));
        NomeDoador.setForeground(new java.awt.Color(0, 0, 0));
        NomeDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeDoadorActionPerformed(evt);
            }
        });

        Nome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Nome.setForeground(new java.awt.Color(0, 0, 0));
        Nome.setText("Nome:");

        Sobrenome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Sobrenome.setForeground(new java.awt.Color(0, 0, 0));
        Sobrenome.setText("Sobrenome:");

        SobreDoador.setBackground(new java.awt.Color(255, 255, 255));
        SobreDoador.setForeground(new java.awt.Color(0, 0, 0));
        SobreDoador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreDoadorActionPerformed(evt);
            }
        });

        Idade.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Idade.setForeground(new java.awt.Color(0, 0, 0));
        Idade.setText("Idade:");

        IdadeDoador.setBackground(new java.awt.Color(255, 255, 255));
        IdadeDoador.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Telefone:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CPF:");

        Titulo.setBackground(new java.awt.Color(255, 255, 0));
        Titulo.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 51));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Danonation");

        BotaoCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        BotaoCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        BotaoCadastrar.setText("CADASTRAR");
        BotaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarActionPerformed(evt);
            }
        });

        CaixadeVerificacao.setText("Não sou um robô");
        CaixadeVerificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixadeVerificacaoActionPerformed(evt);
            }
        });

        BackButton.setBackground(new java.awt.Color(255, 51, 51));
        BackButton.setText("Voltar");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        CPFDoador2.setBackground(new java.awt.Color(255, 255, 255));
        CPFDoador2.setForeground(new java.awt.Color(0, 0, 0));
        CPFDoador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPFDoador2ActionPerformed(evt);
            }
        });
        try{
            MaskFormatter mascararCPF = new MaskFormatter("###.###.###-##");
            mascararCPF.setPlaceholderCharacter('_');
            CPFDoador2 = new javax.swing.JFormattedTextField(mascararCPF);
        }catch(ParseException e){
            e.printStackTrace();
        }

        TelefoneDFormattedTextField.setBackground(new java.awt.Color(255, 255, 255));
        TelefoneDFormattedTextField.setForeground(new java.awt.Color(0, 0, 0));
        TelefoneDFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefoneDFormattedTextFieldActionPerformed(evt);
            }
        });
        try{
            MaskFormatter mascararTel = new MaskFormatter("(##)####-####");
            mascararTel.setPlaceholderCharacter('_');
            TelefoneDFormattedTextField = new javax.swing.JFormattedTextField(mascararTel);
        }catch(ParseException e){
            e.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(506, 506, 506)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BackButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(839, 839, 839)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CaixadeVerificacao)
                            .addComponent(BotaoCadastrar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Idade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IdadeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Nome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NomeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(609, 609, 609)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Sobrenome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SobreDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TelefoneDFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(783, 783, 783)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CPFDoador2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(441, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BackButton)
                .addGap(57, 57, 57)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SobreDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sobrenome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CPFDoador2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(CaixadeVerificacao)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TelefoneDFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Idade)
                    .addComponent(IdadeDoador, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(BotaoCadastrar)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeDoadorActionPerformed

    private void SobreDoadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreDoadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SobreDoadorActionPerformed

    private void BotaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarActionPerformed
        // TODO add your handling code here:
        
        String addNomeC = NomeDoador.getText();
        String addSobrenomeC = SobreDoador.getText();
        int addIdade = Integer.parseInt(IdadeDoador.getText().replace(",", "."));
        String addNumeroT = TelefoneDFormattedTextField.getText();
        String addCPFC = CPFDoador2.getText();
        
        if(CaixadeVerificacao.isSelected()){
        
        if(addNomeC.isEmpty() || addSobrenomeC.isEmpty() || addIdade == 0 || addNumeroT.isEmpty() || addCPFC.isEmpty()){
            
            JOptionPane.showMessageDialog(this, "Por favor preencha todos os campos","ERRO",JOptionPane.ERROR_MESSAGE);
            
        }else{
            
            Doador novoDoador = new Doador(addNomeC,addSobrenomeC,addIdade,addNumeroT,addCPFC);
            DoadorDAO doaDao;
            
            try{
                
                doaDao = new DoadorDAO();
                int res = doaDao.InserirDoador(novoDoador);
               
                if(res == 1){
                    
                   JOptionPane.showMessageDialog(this, "Cadastro feito com sucesso!","SUCESSO",JOptionPane.INFORMATION_MESSAGE);
                   this.clearForm();
                   loadUserData(); //Carregamento de dados do usuario
                   
                }else{
                    
                    JOptionPane.showMessageDialog(this, "O doador já existe" ,"!!!" ,JOptionPane.INFORMATION_MESSAGE);
                    JOptionPane.showMessageDialog(this, "Erro ocorrido ao inserir o cadastro","ERRO",JOptionPane.ERROR_MESSAGE);
                    
                }
                
            }catch(SQLException e){
                //System.out.println(e);
                //JOptionPane.showMessageDialog(this, "c" ,"c" ,JOptionPane.INFORMATION_MESSAGE);
                JOptionPane.showMessageDialog(this, "Erro ocorrido ao inserir o cadastro","ERRO",JOptionPane.ERROR_MESSAGE);
                
            }
            
        }
        
        //ListaDonations ld = new ListaDonations();
        //ld.setVisible(true);
        //dispose();
        }else{
            
            JOptionPane.showMessageDialog(this, "Você é um robô?","",JOptionPane.INFORMATION_MESSAGE);
            
        }
        
    }//GEN-LAST:event_BotaoCadastrarActionPerformed

    private void CaixadeVerificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixadeVerificacaoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_CaixadeVerificacaoActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        
        MenuInicial mi = new MenuInicial();
        mi.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_BackButtonActionPerformed

    private void CPFDoador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPFDoador2ActionPerformed
        // TODO add your handling code here:
        
        String addNomeC = NomeDoador.getText();
        String addSobrenomeC = SobreDoador.getText();
        int addIdade = Integer.parseInt(IdadeDoador.getText().replace(",", "."));
        String addNumeroT = TelefoneDFormattedTextField.getText();
        String addCPFC = CPFDoador2.getText();
        
    }//GEN-LAST:event_CPFDoador2ActionPerformed

    private void TelefoneDFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefoneDFormattedTextFieldActionPerformed
        // TODO add your handling code here:
        
        String addNomeC = NomeDoador.getText();
        String addSobrenomeC = SobreDoador.getText();
        int addIdade = Integer.parseInt(IdadeDoador.getText().replace(",", "."));
        String addNumeroT = TelefoneDFormattedTextField.getText();
        String addCPFC = CPFDoador2.getText();
        
    }//GEN-LAST:event_TelefoneDFormattedTextFieldActionPerformed

    private void clearForm() {
        
        NomeDoador.setText("");
        SobreDoador.setText("");
        IdadeDoador.setText("");
        TelefoneDFormattedTextField.setText("");
        //IdadeDoador.setText("");
        CPFDoador2.setText("");
        
    }

    private void loadUserData() throws SQLException { 
        
        DoadorDAO doaDao = new DoadorDAO();
        List<Doador> doadores = doaDao.getDoador();
        Object[][] data = new Object[doadores.size()][5];
        
        //Preenchendo a tabela (colunas e linhas)
        for (int i = 0; i < doadores.size(); i++) {
            
            data[i][0] = String.valueOf(doadores.get(i).getCpf());
            data[i][1] = doadores.get(i).getNomeDoa();
            data[i][2] = doadores.get(i).getSobreDoa();
            data[i][3] = doadores.get(i).getIdade();
            data[i][4] = doadores.get(i).getNumeroT();
            //data[i][5] = doadores.get(i).getInfID();
            
        }
        
        String[] nomeColuna = {"Nome","Sobrenome","Idade","Telefone","CPF"};
        //Tabela_Doacoes.setModel(new javax.swing.table.DefaultTableModel(data,nomeColuna));
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BotaoCadastrar;
    private javax.swing.JFormattedTextField CPFDoador2;
    private javax.swing.JCheckBox CaixadeVerificacao;
    private javax.swing.JLabel Idade;
    private javax.swing.JTextField IdadeDoador;
    private javax.swing.JLabel Nome;
    private javax.swing.JTextField NomeDoador;
    private javax.swing.JTextField SobreDoador;
    private javax.swing.JLabel Sobrenome;
    private javax.swing.JFormattedTextField TelefoneDFormattedTextField;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
