
package projetoint;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author pedro
 */
public class Menu2 extends javax.swing.JFrame {

    /**
     * Creates new form Menu2
     */
    private int IdDoacaoSelecionado = -1;
    public Menu2() {
        initComponents();
        try {
            loadUserData();
            
        } catch (SQLException ex) {
            Logger.getLogger(Menu2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        setTitle("Tela Cheia");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        // --- CÓDIGO PARA TELA CHEIA ---
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        // ------------------------------
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Nome_do_Doador = new javax.swing.JLabel();
        Quantidade = new javax.swing.JLabel();
        Item = new javax.swing.JLabel();
        Quantidade1 = new javax.swing.JLabel();
        NomeD = new javax.swing.JTextField();
        QuantD = new javax.swing.JTextField();
        ItemD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ButtonVoltar = new javax.swing.JButton();
        ButtonDoar = new javax.swing.JButton();
        CaixadeVerificacao = new javax.swing.JCheckBox();
        CPF = new javax.swing.JLabel();
        cpfOFormattedTextField = new javax.swing.JFormattedTextField();
        DataOFormattedTextField = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela_Doacoes = new javax.swing.JTable();

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Menu"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(51, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1900, 340));

        Titulo.setBackground(new java.awt.Color(102, 102, 255));
        Titulo.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(51, 102, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Danonation");

        Nome_do_Doador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nome_do_Doador.setForeground(new java.awt.Color(0, 0, 0));
        Nome_do_Doador.setText("Nome do Doador:");

        Quantidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Quantidade.setForeground(new java.awt.Color(0, 0, 0));
        Quantidade.setText("Data da doação:");

        Item.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Item.setForeground(new java.awt.Color(0, 0, 0));
        Item.setText("Item:");

        Quantidade1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Quantidade1.setForeground(new java.awt.Color(0, 0, 0));
        Quantidade1.setText("Quantidade:");

        NomeD.setBackground(new java.awt.Color(255, 255, 255));
        NomeD.setForeground(new java.awt.Color(0, 0, 0));
        NomeD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeDActionPerformed(evt);
            }
        });

        QuantD.setBackground(new java.awt.Color(255, 255, 255));
        QuantD.setForeground(new java.awt.Color(0, 0, 0));
        QuantD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantDActionPerformed(evt);
            }
        });

        ItemD.setBackground(new java.awt.Color(255, 255, 255));
        ItemD.setForeground(new java.awt.Color(0, 0, 0));
        ItemD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemDActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));

        ButtonVoltar.setBackground(new java.awt.Color(255, 0, 0));
        ButtonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonVoltar.setText("Voltar");
        ButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVoltarActionPerformed(evt);
            }
        });

        ButtonDoar.setBackground(new java.awt.Color(51, 102, 255));
        ButtonDoar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonDoar.setForeground(new java.awt.Color(0, 0, 0));
        ButtonDoar.setText("Doar");
        ButtonDoar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDoarActionPerformed(evt);
            }
        });

        CaixadeVerificacao.setText("Não sou um robô");
        CaixadeVerificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixadeVerificacaoActionPerformed(evt);
            }
        });

        CPF.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CPF.setForeground(new java.awt.Color(0, 0, 0));
        CPF.setText("CPF:");

        cpfOFormattedTextField.setBackground(new java.awt.Color(255, 255, 255));
        cpfOFormattedTextField.setForeground(new java.awt.Color(0, 0, 0));
        cpfOFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfOFormattedTextFieldActionPerformed(evt);
            }
        });
        try{
            MaskFormatter mascararCPF = new MaskFormatter("###.###.###-##");
            mascararCPF.setPlaceholderCharacter('_');
            cpfOFormattedTextField = new javax.swing.JFormattedTextField(mascararCPF);
        }catch(ParseException e){
            e.printStackTrace();
        }

        DataOFormattedTextField.setBackground(new java.awt.Color(255, 255, 255));
        DataOFormattedTextField.setForeground(new java.awt.Color(0, 0, 0));
        DataOFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataOFormattedTextFieldActionPerformed(evt);
            }
        });
        try{
            MaskFormatter mascararDat = new MaskFormatter("####/##/##");
            mascararDat.setPlaceholderCharacter('_');
            DataOFormattedTextField = new javax.swing.JFormattedTextField(mascararDat);
        }catch(ParseException e){
            e.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ButtonVoltar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Quantidade1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(QuantD, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Nome_do_Doador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeD, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(370, 370, 370)
                                .addComponent(CaixadeVerificacao))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(329, 329, 329)
                                .addComponent(CPF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpfOFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 464, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Item)
                        .addGap(4, 4, 4)
                        .addComponent(ItemD, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Quantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DataOFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(137, 137, 137))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(559, 559, 559))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonDoar)
                        .addGap(937, 937, 937))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(ButtonVoltar)
                .addGap(10, 10, 10)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nome_do_Doador, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NomeD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Item, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Quantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(QuantD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CPF)
                            .addComponent(cpfOFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(ButtonDoar)
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CaixadeVerificacao)
                            .addComponent(Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DataOFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)))
                .addGap(81, 81, 81))
        );

        Titulo.getAccessibleContext().setAccessibleParent(Titulo);
        Nome_do_Doador.getAccessibleContext().setAccessibleParent(Nome_do_Doador);
        Quantidade.getAccessibleContext().setAccessibleParent(Quantidade);
        Item.getAccessibleContext().setAccessibleParent(Item);

        Tabela_Doacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Item", "Quantidade", "Data", "CPF"
            }
        ));
        Tabela_Doacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_DoacoesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela_Doacoes);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1952, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeDActionPerformed

    private void QuantDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantDActionPerformed

    private void ItemDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemDActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void ButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVoltarActionPerformed
        // TODO add your handling code here:
        
        MenuInicial mi = new MenuInicial();
        mi.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_ButtonVoltarActionPerformed

    private void ButtonDoarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDoarActionPerformed
        // TODO add your handling code here:
        
        String addNomeD = NomeD.getText();
        String addItemD = ItemD.getText();
        int addQuantidadeD = Integer.parseInt(QuantD.getText().replace(",", "."));
        String addDataVD = DataOFormattedTextField.getText();
        String addCPFO = cpfOFormattedTextField.getText();
        
        if(CaixadeVerificacao.isSelected()){
        
        if(addNomeD.isEmpty() || addItemD.isEmpty() || addQuantidadeD == 0 || addDataVD.isEmpty() || addCPFO.isEmpty()){
            
            JOptionPane.showMessageDialog(this, "Por favor preencha todos os campos","ERRO",JOptionPane.ERROR_MESSAGE);
            
        }else{
            
            Outros novoOutros = new Outros(0, addNomeD,addItemD,addQuantidadeD,addDataVD, addCPFO);
            OutrosDAO outDao;
            
            try{
                
                outDao = new OutrosDAO();
                int res = outDao.InserirOutros(novoOutros);
               
                if(res == 1){
                    
                   JOptionPane.showMessageDialog(this, "Doação criado com sucesso!","SUCESSO",JOptionPane.INFORMATION_MESSAGE);
                   this.clearForm();
                   loadUserData(); //Carregamento de dados do usuario
                   
                }else{
                    
                    JOptionPane.showMessageDialog(this, "Erro ocorrido ao inserir a doação","ERRO",JOptionPane.ERROR_MESSAGE);
                    
                }
                
            }catch(SQLException e){
                //System.out.println(e);
                //JOptionPane.showMessageDialog(this, "c" ,"c" ,JOptionPane.INFORMATION_MESSAGE);
                JOptionPane.showMessageDialog(this, "Erro ocorrido ao inserir a doação","ERRO",JOptionPane.ERROR_MESSAGE);
                
            }
            
        }
        
        //ListaDonations ld = new ListaDonations();
        //ld.setVisible(true);
        //dispose();
        }else{
            
            JOptionPane.showMessageDialog(this, "Você é um robô?","",JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_ButtonDoarActionPerformed

    private void Tabela_DoacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_DoacoesMouseClicked
        // TODO add your handling code here:
        
        int LinhaSelecionada = Tabela_Doacoes.getSelectedRow();
        
        if(LinhaSelecionada != -1){
            
            IdDoacaoSelecionado = Integer.parseInt(Tabela_Doacoes.getValueAt(LinhaSelecionada, 0).toString());
            NomeD.setText(Tabela_Doacoes.getValueAt(LinhaSelecionada, 1).toString());
            ItemD.setText(Tabela_Doacoes.getValueAt(LinhaSelecionada, 2).toString());
            QuantD.setText(Tabela_Doacoes.getValueAt(LinhaSelecionada, 3).toString());
            DataOFormattedTextField.setText(Tabela_Doacoes.getValueAt(LinhaSelecionada, 4).toString());
            cpfOFormattedTextField.setText(Tabela_Doacoes.getValueAt(LinhaSelecionada, 5).toString());
        }
        
    }//GEN-LAST:event_Tabela_DoacoesMouseClicked

    private void CaixadeVerificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixadeVerificacaoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CaixadeVerificacaoActionPerformed

    private void cpfOFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfOFormattedTextFieldActionPerformed
        // TODO add your handling code here:
        
        String addNomeD = NomeD.getText();
        String addItemD = ItemD.getText();
        int addQuantidadeD = Integer.parseInt(QuantD.getText().replace(",", "."));
        String addDataVD = DataOFormattedTextField.getText();
        String addCPFO = cpfOFormattedTextField.getText();
    }//GEN-LAST:event_cpfOFormattedTextFieldActionPerformed

    private void DataOFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataOFormattedTextFieldActionPerformed
        // TODO add your handling code here:
        String addNomeD = NomeD.getText();
        String addItemD = ItemD.getText();
        int addQuantidadeD = Integer.parseInt(QuantD.getText().replace(",", "."));
        String addDataVD = DataOFormattedTextField.getText();
        String addCPFO = cpfOFormattedTextField.getText();
        
    }//GEN-LAST:event_DataOFormattedTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu2().setVisible(true);
            }
        });
    }
    
    private void clearForm() {
        
        NomeD.setText("");
        ItemD.setText("");
        QuantD.setText("");
        DataOFormattedTextField.setText("");
        cpfOFormattedTextField.setText("");
    }

    private void loadUserData() throws SQLException { 
        
        OutrosDAO outDao = new OutrosDAO();
        List<Outros> outros = outDao.getOutros();
        Object[][] data = new Object[outros.size()][6];
        
        //Preenchendo a tabela (colunas e linhas)
        for (int i = 0; i < outros.size(); i++) {
            
            data[i][0] = String.valueOf(outros.get(i).getId());
            data[i][1] = outros.get(i).getNome();
            data[i][2] = outros.get(i).getItem();
            data[i][3] = outros.get(i).getQuantidade();
            data[i][4] = outros.get(i).getDatastring();
            data[i][5] = outros.get(i).getInfID();
            
        }
        
        String[] nomeColuna = {"Id","Nome","Item","Quantidade","Data","CPF"};
        Tabela_Doacoes.setModel(new javax.swing.table.DefaultTableModel(data,nomeColuna));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDoar;
    private javax.swing.JButton ButtonVoltar;
    private javax.swing.JLabel CPF;
    private javax.swing.JCheckBox CaixadeVerificacao;
    private javax.swing.JFormattedTextField DataOFormattedTextField;
    private javax.swing.JLabel Item;
    private javax.swing.JTextField ItemD;
    private javax.swing.JTextField NomeD;
    private javax.swing.JLabel Nome_do_Doador;
    private javax.swing.JTextField QuantD;
    private javax.swing.JLabel Quantidade;
    private javax.swing.JLabel Quantidade1;
    private javax.swing.JTable Tabela_Doacoes;
    private javax.swing.JLabel Titulo;
    private javax.swing.JFormattedTextField cpfOFormattedTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
