
package projetoint;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author pedro
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private int IdDoacaoSelecionado = -1;
    public Menu() {
        initComponents();
        try {
            loadUserData();
            
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        setTitle("");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Nome_do_Doador = new javax.swing.JLabel();
        Quantidade = new javax.swing.JLabel();
        Item = new javax.swing.JLabel();
        Quantidade1 = new javax.swing.JLabel();
        NomeF = new javax.swing.JTextField();
        PesoF = new javax.swing.JTextField();
        ItemF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ButtonVoltar = new javax.swing.JButton();
        ButtonDoar = new javax.swing.JButton();
        CaixadeVerificacao = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        cpfFFormattedTextField = new javax.swing.JFormattedTextField();
        DataFormattedTextField = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela_Doacoes = new javax.swing.JTable();

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Menu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 400));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(51, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1900, 340));

        Titulo.setBackground(new java.awt.Color(0, 255, 0));
        Titulo.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 255, 0));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Danonation");

        Nome_do_Doador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nome_do_Doador.setForeground(new java.awt.Color(0, 0, 0));
        Nome_do_Doador.setText("Nome do Doador:");

        Quantidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Quantidade.setForeground(new java.awt.Color(0, 0, 0));
        Quantidade.setText("Data de doação:");

        Item.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Item.setForeground(new java.awt.Color(0, 0, 0));
        Item.setText("Alimento:");

        Quantidade1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Quantidade1.setForeground(new java.awt.Color(0, 0, 0));
        Quantidade1.setText("Peso:");

        NomeF.setBackground(new java.awt.Color(255, 255, 255));
        NomeF.setForeground(new java.awt.Color(0, 0, 0));
        NomeF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeFActionPerformed(evt);
            }
        });

        PesoF.setBackground(new java.awt.Color(255, 255, 255));
        PesoF.setForeground(new java.awt.Color(0, 0, 0));
        PesoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesoFActionPerformed(evt);
            }
        });

        ItemF.setBackground(new java.awt.Color(255, 255, 255));
        ItemF.setForeground(new java.awt.Color(0, 0, 0));
        ItemF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemFActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));

        ButtonVoltar.setBackground(new java.awt.Color(255, 0, 0));
        ButtonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        ButtonVoltar.setText("Voltar");
        ButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVoltarActionPerformed(evt);
            }
        });

        ButtonDoar.setBackground(new java.awt.Color(0, 255, 0));
        ButtonDoar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ButtonDoar.setForeground(new java.awt.Color(0, 0, 0));
        ButtonDoar.setText("Doar");
        ButtonDoar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDoarActionPerformed(evt);
            }
        });

        CaixadeVerificacao.setText("Não sou um robô");
        CaixadeVerificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixadeVerificacaoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CPF:");

        cpfFFormattedTextField.setBackground(new java.awt.Color(255, 255, 255));
        cpfFFormattedTextField.setForeground(new java.awt.Color(0, 0, 0));
        cpfFFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfFFormattedTextFieldActionPerformed(evt);
            }
        });
        try{
            MaskFormatter mascararCPF = new MaskFormatter("###.###.###-##");
            mascararCPF.setPlaceholderCharacter('_');
            cpfFFormattedTextField = new javax.swing.JFormattedTextField(mascararCPF);
        }catch(ParseException e){
            e.printStackTrace();
        }

        DataFormattedTextField.setBackground(new java.awt.Color(255, 255, 255));
        DataFormattedTextField.setForeground(new java.awt.Color(0, 0, 0));
        DataFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DataFormattedTextFieldActionPerformed(evt);
            }
        });
        try{
            MaskFormatter mascararDat = new MaskFormatter("####/##/##");
            mascararDat.setPlaceholderCharacter('_');
            DataFormattedTextField = new javax.swing.JFormattedTextField(mascararDat);
        }catch(ParseException e){
            e.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonVoltar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(299, 299, 299)
                                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Quantidade)
                                        .addGap(18, 18, 18)
                                        .addComponent(DataFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Nome_do_Doador)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(NomeF, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(347, 347, 347)
                                                .addComponent(ButtonDoar))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(274, 274, 274)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cpfFFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Quantidade1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(PesoF, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Item)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ItemF, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(310, 310, 310))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(863, 863, 863)
                .addComponent(CaixadeVerificacao)
                .addContainerGap(1114, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(ButtonVoltar)
                .addGap(9, 9, 9)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nome_do_Doador, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NomeF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(cpfFFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73)
                        .addComponent(ButtonDoar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DataFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Item, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ItemF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(135, 135, 135))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Quantidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PesoF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(CaixadeVerificacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        Titulo.getAccessibleContext().setAccessibleParent(Titulo);
        Nome_do_Doador.getAccessibleContext().setAccessibleParent(Nome_do_Doador);
        Quantidade.getAccessibleContext().setAccessibleParent(Quantidade);
        Item.getAccessibleContext().setAccessibleParent(Item);

        Tabela_Doacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome do Doador", "Alimento", "Peso", "Data", "CPF"
            }
        ));
        Tabela_Doacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_DoacoesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela_Doacoes);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2093, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeFActionPerformed

    private void PesoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesoFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PesoFActionPerformed

    private void ItemFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemFActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void ButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVoltarActionPerformed
        // TODO add your handling code here:
        
        MenuInicial mi = new MenuInicial();
        mi.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_ButtonVoltarActionPerformed

    private void ButtonDoarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDoarActionPerformed
        // TODO add your handling code here:
        
        String addNomeF = NomeF.getText();
        String addItemF = ItemF.getText();
        double addQuantidadeF = Double.parseDouble(PesoF.getText().replace("", ""));
        String addDataVDF = DataFormattedTextField.getText();
        String addCPFF = cpfFFormattedTextField.getText();
        
        
        if(CaixadeVerificacao.isSelected()){
        
        if(addNomeF.isEmpty() || addItemF.isEmpty() || addQuantidadeF == 0 || addDataVDF.isEmpty() || addCPFF.isEmpty()){
            
            JOptionPane.showMessageDialog(this, "Por favor preencha todos os campos","ERRO",JOptionPane.ERROR_MESSAGE);
            
        }else{
            
            Food novoFood = new Food(0, addNomeF,addItemF,addQuantidadeF,addDataVDF,addCPFF);
            FoodDAO fodDao;
            
            try{
                
                fodDao = new FoodDAO();
                int res = fodDao.InserirFood(novoFood);
               
                if(res == 1){
                    
                   JOptionPane.showMessageDialog(this, "Doação criado com sucesso!","SUCESSO",JOptionPane.INFORMATION_MESSAGE);
                   this.clearForm();
                   loadUserData(); //Carregamento de dados do usuario
                   
                }else{
                    
                    JOptionPane.showMessageDialog(this, "Erro ocorrido ao inserir a doação","ERRO",JOptionPane.ERROR_MESSAGE);
                    
                }
                
            }catch(SQLException e){
                //System.out.println(e);
                //JOptionPane.showMessageDialog(this, "c" ,"c" ,JOptionPane.INFORMATION_MESSAGE);
                JOptionPane.showMessageDialog(this, "Erro ocorrido ao inserir a doação","ERRO",JOptionPane.ERROR_MESSAGE);
                
            }
            
        }
        
        //ListaDonations ld = new ListaDonations();
        //ld.setVisible(true);
        //dispose();
        }else{
            
            JOptionPane.showMessageDialog(this, "Você é um robô?","",JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_ButtonDoarActionPerformed

    private void Tabela_DoacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_DoacoesMouseClicked
        // TODO add your handling code here:
        
        int LinhaSelecionada = Tabela_Doacoes.getSelectedRow();
        
        if(LinhaSelecionada != -1){
            
            IdDoacaoSelecionado = Integer.parseInt(Tabela_Doacoes.getValueAt(LinhaSelecionada, 0).toString());
            NomeF.setText(Tabela_Doacoes.getValueAt(LinhaSelecionada, 1).toString());
            ItemF.setText(Tabela_Doacoes.getValueAt(LinhaSelecionada, 2).toString());
            PesoF.setText(Tabela_Doacoes.getValueAt(LinhaSelecionada, 3).toString());
            DataFormattedTextField.setText(Tabela_Doacoes.getValueAt(LinhaSelecionada, 4).toString());
            cpfFFormattedTextField.setText(Tabela_Doacoes.getValueAt(LinhaSelecionada, 5).toString());
            
        }
        
    }//GEN-LAST:event_Tabela_DoacoesMouseClicked

    private void CaixadeVerificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixadeVerificacaoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CaixadeVerificacaoActionPerformed

    private void cpfFFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfFFormattedTextFieldActionPerformed
        // TODO add your handling code here:
        
        String addNomeF = NomeF.getText();
        String addItemF = ItemF.getText();
        double addQuantidadeF = Double.parseDouble(PesoF.getText().replace("", ""));
        String addDataVDF = DataFormattedTextField.getText();
        String addCPFF = cpfFFormattedTextField.getText();
        
    }//GEN-LAST:event_cpfFFormattedTextFieldActionPerformed

    private void DataFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DataFormattedTextFieldActionPerformed
        // TODO add your handling code here:
        String addNomeF = NomeF.getText();
        String addItemF = ItemF.getText();
        double addQuantidadeF = Double.parseDouble(PesoF.getText().replace("", ""));
        String addDataVDF = DataFormattedTextField.getText();
        String addCPFF = cpfFFormattedTextField.getText();
        
    }//GEN-LAST:event_DataFormattedTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    private void clearForm() {
        
        NomeF.setText("");
        ItemF.setText("");
        PesoF.setText("");
        DataFormattedTextField.setText("");
        cpfFFormattedTextField.setText("");
        
    }

    private void loadUserData() throws SQLException { 
        
        FoodDAO fodDao = new FoodDAO();
        List<Food> foods = fodDao.getFood();
        Object[][] data = new Object[foods.size()][6];
        
        //Preenchendo a tabela (colunas e linhas)
        for (int i = 0; i < foods.size(); i++) {
            
            data[i][0] = String.valueOf(foods.get(i).getId());
            data[i][1] = foods.get(i).getNomeF();
            data[i][2] = foods.get(i).getComida();
            data[i][3] = foods.get(i).getPeso();
            data[i][4] = foods.get(i).getDataFstring();
            data[i][5] = foods.get(i).getInfID();
            
        }
        
        Object[] nomeColuna = {"Id","Nome do Doador","Alimento","Peso","Data","CPF"};
        Tabela_Doacoes.setModel(new javax.swing.table.DefaultTableModel(data,nomeColuna));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonDoar;
    private javax.swing.JButton ButtonVoltar;
    private javax.swing.JCheckBox CaixadeVerificacao;
    private javax.swing.JFormattedTextField DataFormattedTextField;
    private javax.swing.JLabel Item;
    private javax.swing.JTextField ItemF;
    private javax.swing.JTextField NomeF;
    private javax.swing.JLabel Nome_do_Doador;
    private javax.swing.JTextField PesoF;
    private javax.swing.JLabel Quantidade;
    private javax.swing.JLabel Quantidade1;
    private javax.swing.JTable Tabela_Doacoes;
    private javax.swing.JLabel Titulo;
    private javax.swing.JFormattedTextField cpfFFormattedTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
